import fs from 'fs';
import path from 'path';

import { adapterManifestTemplate, type AdapterKind, type AdapterManifest } from './manifest.js';

export interface AdapterInitOptions {
  type: AdapterKind;
  name: string;
  outDir?: string;
}

export interface AdapterInitResult {
  adapterDir: string;
  files: string[];
}

function ensureSafeName(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) {
    throw new Error('Adapter name must be a non-empty string.');
  }
  if (!/^[a-zA-Z0-9_-]+$/.test(trimmed)) {
    throw new Error('Adapter name may only contain letters, numbers, hyphen, and underscore.');
  }
  return trimmed;
}

function buildManifest(type: AdapterKind, name: string): AdapterManifest {
  const entry = type === 'cli'
    ? './runner.sh'
    : type === 'python'
      ? './runner.py'
      : './runner.mjs';

  return {
    ...adapterManifestTemplate,
    id: name,
    kind: type,
    entry,
    supportedBenchmarks: type === 'python' ? ['tau'] : ['swe'],
    capabilities: {
      ...adapterManifestTemplate.capabilities,
      runModes: type === 'python' ? ['session'] : ['task'],
      supportsTrajectory: type === 'python',
      supportsToolCallTrace: type !== 'cli',
      supportsPatchOutput: type !== 'python',
    },
  };
}

function renderCliRunner(): string {
  return `#!/usr/bin/env bash
set -euo pipefail

if [[ -n "\${KBENCH_ADAPTER_INPUT:-}" ]]; then
  input="$(cat "$KBENCH_ADAPTER_INPUT")"
else
  input="$(cat)"
fi

if printf '%s' "$input" | grep -q '"mode":"session"'; then
  cat <<'EOF'
{"ok":true,"status":"ok","action":"respond(sample)","finalText":"session stub response","elapsedMs":1,"artifacts":[]}
EOF
else
  cat <<'EOF'
{"ok":true,"status":"ok","finalText":"task stub response","elapsedMs":1,"artifacts":[]}
EOF
fi
`;
}

function renderPythonRunner(): string {
  return `#!/usr/bin/env python3
import json
import os
import sys


def main() -> None:
    if os.environ.get("KBENCH_ADAPTER_INPUT"):
        with open(os.environ["KBENCH_ADAPTER_INPUT"], "r", encoding="utf-8") as handle:
            payload = json.load(handle)
    else:
        payload = json.load(sys.stdin)
    mode = payload.get("mode")
    if mode == "session":
        result = {
            "ok": True,
            "status": "ok",
            "action": "respond(sample)",
            "finalText": "session stub response",
            "elapsedMs": 1,
            "artifacts": [],
        }
    else:
        result = {
            "ok": True,
            "status": "ok",
            "finalText": "task stub response",
            "elapsedMs": 1,
            "artifacts": [],
        }
    json.dump(result, sys.stdout)


if __name__ == "__main__":
    main()
`;
}

function renderNodeRunner(): string {
  return `#!/usr/bin/env node
import { readFileSync } from 'node:fs';
import process from 'node:process';

const input = process.env.KBENCH_ADAPTER_INPUT
  ? readFileSync(process.env.KBENCH_ADAPTER_INPUT, 'utf8')
  : readFileSync(0, 'utf8');
const payload = JSON.parse(input || '{}');
const result = payload.mode === 'session'
  ? {
      ok: true,
      status: 'ok',
      action: 'respond(sample)',
      finalText: 'session stub response',
      elapsedMs: 1,
      artifacts: [],
    }
  : {
      ok: true,
      status: 'ok',
      finalText: 'task stub response',
      elapsedMs: 1,
      artifacts: [],
    };

process.stdout.write(JSON.stringify(result));
`;
}

function renderReadme(name: string, manifest: AdapterManifest): string {
  return `# ${name}

This adapter was generated by \`kbench adapter init\`.

Files:

- \`adapter.manifest.json\`
- \`${manifest.entry.replace('./', '')}\`

Runner contract:

- read one JSON payload from \`$KBENCH_ADAPTER_INPUT\` when present, otherwise stdin
- write one JSON payload to stdout
- follow \`src/harness/sdk/protocol.ts\`

Next steps:

1. Update \`adapter.manifest.json\`
2. Replace the stub runner logic with your real harness bridge
3. Run \`kbench adapter validate --adapter ${path.basename(name)}\`
`;
}

async function writeFile(targetPath: string, content: string, executable = false): Promise<void> {
  await fs.promises.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.promises.writeFile(targetPath, content, 'utf-8');
  if (executable) {
    await fs.promises.chmod(targetPath, 0o755);
  }
}

export async function initAdapter(options: AdapterInitOptions): Promise<AdapterInitResult> {
  const name = ensureSafeName(options.name);
  const adapterDir = path.resolve(options.outDir || path.join(process.cwd(), name));
  const manifest = buildManifest(options.type, name);
  const runnerName = manifest.entry.replace('./', '');
  const runnerContent = options.type === 'cli'
    ? renderCliRunner()
    : options.type === 'python'
      ? renderPythonRunner()
      : renderNodeRunner();

  if (fs.existsSync(adapterDir)) {
    const entries = fs.readdirSync(adapterDir);
    if (entries.length > 0) {
      throw new Error(`Target adapter directory is not empty: ${adapterDir}`);
    }
  }

  await fs.promises.mkdir(adapterDir, { recursive: true });

  const manifestPath = path.join(adapterDir, 'adapter.manifest.json');
  const runnerPath = path.join(adapterDir, runnerName);
  const readmePath = path.join(adapterDir, 'README.md');

  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  await writeFile(runnerPath, runnerContent, true);
  await writeFile(readmePath, `${renderReadme(name, manifest)}\n`);

  return {
    adapterDir,
    files: [manifestPath, runnerPath, readmePath],
  };
}
